name: login_app
description: A simple Flutter login application for PBP task
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^7.0.0
  device_info_plus: ^12.1.0
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  provider: ^6.0.5
  qr_flutter: ^4.0.0          # render QR di widget
  pdf: ^3.10.1               # membuat PDF (struk)
  printing: ^5.10.0          # cetak / save PDF (komunikasi printer)
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  shared_preferences: ^2.5.3

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  
  assets:
    - assets/images/fais.png
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/background1.png
    - assets/images/carrier60L.png
    - assets/images/backgroundkomporportable.png
    - assets/images/komporportable.png
    - assets/images/Tenda.png
    - assets/images/backgroundsleepingbag.png
    - assets/images/sleepingbag.png
    - assets/images/Sepatu.png
    - assets/images/Hydropack.png
    - assets/images/backgroundheadlamp.png
    - assets/images/Headlamp.png
    - assets/images/Diskon.png
    - assets/images/Outdoor.png
    - assets/images/Mountain.png
    - assets/images/backgroundsepatu.png
    - assets/images/Sepatu2.png
    - assets/images/Sepatu3.png
    - assets/images/Sepatu5.png
    - assets/images/backgroundtenda.jpg
    - assets/images/Tenda2.png
    - assets/images/backgroundhydropack.png
    - assets/images/backgroundcarrier.png
    - assets/images/carrier.png
    - assets/images/carrier2.png
    - assets/images/backgroundjacket.jpg
    - assets/images/jacket1.png
    - assets/images/jacket2.png
    - assets/images/jacket3.png
    - assets/images/backgroundsarungtangan.png
    - assets/images/Sarungtangan.png
    - assets/images/backgroundtrackingpole.png
    - assets/images/trackingpole1.png
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

    
