name: login_app
description: A simple Flutter login application for PBP task
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^7.0.0
  device_info_plus: ^12.1.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/background1.png
    - assets/images/carrier60L.png
    - assets/images/komporportable.png
    - assets/images/Tenda.png
    - assets/images/backgroundsleepingbag.png
    - assets/images/sleepingbag.png
    - assets/images/Sepatu.png
    - assets/images/Hydropack.png
    - assets/images/Headlamp.png
    - assets/images/Diskon.png
    - assets/images/Outdoor.png
    - assets/images/Mountain.png
    - assets/images/backgroundsepatu.png
    - assets/images/Sepatu2.png
    - assets/images/Sepatu3.png
    - assets/images/Sepatu5.png
    - assets/images/backgroundtenda.jpg
    - assets/images/Tenda2.png
    - assets/images/backgroundhydropack.png
    - assets/images/backgroundcarrier.png
    - assets/images/carrier.png
    - assets/images/carrier2.png
    - assets/images/backgroundjacket.jpg
    - assets/images/jacket1.png
    - assets/images/jacket2.png
    - assets/images/jacket3.png
    
    
