// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_iuDlQUgw92R7sERMCeWlO-j2vUbdOQE',
    appId: '1:328421537387:web:7a3e41f67c3fc95ef7232e',
    messagingSenderId: '328421537387',
    projectId: 'outdoor-3c33d',
    authDomain: 'outdoor-3c33d.firebaseapp.com',
    storageBucket: 'outdoor-3c33d.firebasestorage.app',
    measurementId: 'G-GY0T7ZK1EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWfSgumF-w2L-hxgL_6h9aWJHPZCIKJR4',
    appId: '1:328421537387:android:888edb2c0bef439bf7232e',
    messagingSenderId: '328421537387',
    projectId: 'outdoor-3c33d',
    storageBucket: 'outdoor-3c33d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEefn-VpHUwl_p5WCew4o2HQBhJoDClP8',
    appId: '1:328421537387:ios:00399bdf5435f900f7232e',
    messagingSenderId: '328421537387',
    projectId: 'outdoor-3c33d',
    storageBucket: 'outdoor-3c33d.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEefn-VpHUwl_p5WCew4o2HQBhJoDClP8',
    appId: '1:328421537387:ios:00399bdf5435f900f7232e',
    messagingSenderId: '328421537387',
    projectId: 'outdoor-3c33d',
    storageBucket: 'outdoor-3c33d.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_iuDlQUgw92R7sERMCeWlO-j2vUbdOQE',
    appId: '1:328421537387:web:571ed862634e5530f7232e',
    messagingSenderId: '328421537387',
    projectId: 'outdoor-3c33d',
    authDomain: 'outdoor-3c33d.firebaseapp.com',
    storageBucket: 'outdoor-3c33d.firebasestorage.app',
    measurementId: 'G-8QBST36MBN',
  );
}
